# Generated by Django 3.1.7 on 2021-03-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210319_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network.followers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network.follows'),
            preserve_default=False,
        ),
    ]
