# Generated by Django 3.1.4 on 2021-01-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='winnder',
            field=models.BooleanField(default=False),
        ),
    ]
