# Generated by Django 3.1.4 on 2021-01-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_winnder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='winnder',
            new_name='winner',
        ),
    ]
