# Generated by Django 3.1.4 on 2021-01-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210114_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='winner',
        ),
        migrations.AddField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='closing_bid',
            field=models.IntegerField(default=0),
        ),
    ]
